### ISSUE TITLE
Некорректно отображается статистика за год

### ISSUE THREAD

**Issue by bircoph** [VelFleX/JetLend-Extension#2]
Добрый день!

При сроке инвестирования меньше года ожидаемо, что статистика за всё время и за год будет одинаковой; однако, они различаются в поле "процентный доход".  Значение процентного дохода "за всё время" правильное и совпадает со значением на главной странице (в т.ч. без плагина), а вот значение за весь год несколько больше: иногда на сумму дохода на вторичке и пени, иногда меньше этой суммы.

Проблема возникла в версии 0.6.0 и продолжает наблюдаться в 0.6.1.

По коду я вижу, что данные берутся из userStats.data.data.summary_year, так что, быть может, это баг JL или проблемы с кэшем.

**Comment by VelFleX** [comment]
Баг джета, добавил заглушку.
