### ISSUE TITLE
Ошибка переключения срока отображения данных.

### ISSUE THREAD

**Issue by Zerg17** [VelFleX/JetLend-Extension#3]
При нажатии на "Отображать данные за **_год_**", переключает на "Отображать данные за **_все время_**", но обратно вернуться на "Отображать данные за **_год_**" нельзя. Просто ничего не происходит при нажатии.

**Comment by Zerg17** [comment]
Я так понимаю оно происходит из-за условия investDays() >= 365 (файл popup.js, строка 222). Если так и задумывалось что нельзя переключать на год если срок инвестирования меньше года, то при первом запуске тоже должно быть за все время, а не за год.

**Comment by VelFleX** [comment]
Да, именно так я и задумывалось. Я думаю, что проблема может быть связана с кэшем из-за установки новой версии поверх старой. Сейчас я попробовал установить актуальную версию с чистого листа, явно указав ограничение срока инвестирования больше, чем мой собственный. И я не заметил данной ошибки.
